Mr 19 cov forest tab
CRSU-Apps/MetaInsight pull request #105
Opened 2023-11-21 16:31 UTC by BalancedmonkeY

Work involved further modularising of the base app - so may want to view changes by individual commits, or most recent three, to see more detailed changes.

2023-11-22 11:07 UTC, tommorris168 requested changes
All code looks good, and the things I can try all work. There are some things I can't try until they are implemented, e.g. sensitivity analysis.
Please change the function names to upper camel case where they aren't already (unless this interferes with existing code).

2023-11-22 11:07 UTC, tommorris168 commented on R/gemtc_analysis.R
`paste0("Value for covariate ", model$model$regressor$variable, " set at ", cov_value)`
Can we have this displayed in the app as well as in the download?

2023-11-22 11:09 UTC, tommorris168 commented on R/gemtc_analysis.R
Just seen on Jira this is to be done later.

2023-11-23 13:20 UTC, BalancedmonkeY commented
> All code looks good, and the things I can try all work. There are some things I can't try until they are implemented, e.g. sensitivity analysis. Please change the function names to upper camel case where they aren't already (unless this interferes with existing code).

I have changed some functions (and variable names) to follow the style guide. However, I haven't changed the Shiny module functions to upper camel case as they are a bit different. Janion hopes to chat about this on Friday.

2023-11-23 13:29 UTC, BalancedmonkeY commented on R/bayesian/base tab/forest_plot_page.R
This was historic code - probably from how it was built up. Changed to use outcome_measure and feed up through the modules.

2023-11-23 13:30 UTC, BalancedmonkeY commented on R/bayesian/base tab/forest_plot_page.R
Done

2023-11-23 13:33 UTC, BalancedmonkeY commented on R/bayesian/base tab/forest_plot_page.R
Done

2023-11-23 13:34 UTC, BalancedmonkeY commented on R/bayesian/forest_plot_plus_stats.R
Done

2023-11-23 13:35 UTC, BalancedmonkeY commented on R/gemtc_analysis.R
Yes, as it will be visible via the options above every tab - I didn't think it was necessary to be printed on the screen.

2023-11-24 10:48 UTC, tommorris168 requested changes
The step in `numericInput` isn't updating if you do a new analysis without closing the app, so please add the step change to the `updateNumericInput` functions in `bayesian_forest_plot_plus_stats_server` in _forest_plot_plus_stats.R_.

The new name of `gemtctau` in _fn_analysis.R_ will cause a conflict when merging into dev, because this function is no longer in _fn_analysis.R_. Might not be a problem.

I don't think the warnings in _covariate tab/forest_plot_page.R_ will ever be displayed, because the analysis is blocked when you select the radio button for one of the unimplemented analyses. If you want to ignore this for now I'm happy to approve, but the redundant code should be removed at some point.

2023-11-28 10:43 UTC, BalancedmonkeY commented
> The step in `numericInput` isn't updating if you do a new analysis without closing the app, so please add the step change to the `updateNumericInput` functions in `bayesian_forest_plot_plus_stats_server` in _forest_plot_plus_stats.R_.
> 
> The new name of `gemtctau` in _fn_analysis.R_ will cause a conflict when merging into dev, because this function is no longer in _fn_analysis.R_. Might not be a problem.
> 
> I don't think the warnings in _covariate tab/forest_plot_page.R_ will ever be displayed, because the analysis is blocked when you select the radio button for one of the unimplemented analyses. If you want to ignore this for now I'm happy to approve, but the redundant code should be removed at some point.

Good spot on the `updateNumericInput` - thanks. I've also removed the warning for the covariate analysis as you're right, its not needed.
For now, the feature branch doesn't have those changes, so the renaming of `gemtctau` should be okay for now. But I have done some rearranging to help with the eventual merge.

2023-11-28 15:15 UTC, JanionNevill commented
> The step in `numericInput` isn't updating if you do a new analysis without closing the app, so please add the step change to the `updateNumericInput` functions in `bayesian_forest_plot_plus_stats_server` in _forest_plot_plus_stats.R_.

You added steps to the min, but not the max. Was there a reason for this?

2023-11-28 15:18 UTC, JanionNevill requested changes
Just a minor question

2023-11-28 17:17 UTC, BalancedmonkeY commented
> > The step in `numericInput` isn't updating if you do a new analysis without closing the app, so please add the step change to the `updateNumericInput` functions in `bayesian_forest_plot_plus_stats_server` in _forest_plot_plus_stats.R_.
> 
> You added steps to the min, but not the max. Was there a reason for this?
> 
> ### EDIT:
> After discussion, it was realised that the checks should be on the outcome measure, not the meta outcome. Please changes this to reflect better when the measure is logarithmic or linear.
> 
> While you're there....
> 
> * The formatting is inconsistent with spaces around the `=`.
> * The If statement should also have and `else` statement to throw an error if the outcome is not one of the supported options.
> * The reactive doesn't need to be assigned to a variable `x` at the beginning, it can just be called in each relevant location.

Implemented all this. However, for RD, MD, and SMD, the lower limit will step up by 0.1 first, then 1 onwards. I don't really know why it's doing this, and is something the app already does...

2023-11-29 09:56 UTC, JanionNevill approved these changes
Made minor changes. Otherwise all looks good.

2023-12-04 11:02 UTC, JanionNevill approved these changes
I've removed the default covariate value from the value panel. Everything else looks good.

2023-12-04 12:46 UTC, tommorris168 requested changes
For the box/button where you enter the covariate value, there needs to be some text to say that's what it is. Also, I'm not convinced it's in the best place. I would have put it lower down, say underneath the "choose type of regression coefficient" selection box. This might also sort out the alignment, because it's currently slightly too high. If other people prefer the current position I'm happy to leave it.

Can we reorder the options in the "choose type of regression coefficient" selection box? I would have put them in order of the number of parameters, i.e. shared, exchangeable, unrelated (or the reverse).

2023-12-05 10:16 UTC, tommorris168 approved these changes

2023-12-05 10:37 UTC, merged