Mr 27 contribution plot
CRSU-Apps/MetaInsight pull request #115
Opened 2023-12-14 14:00 UTC by JanionNevill

Created indirect contribution plot and composite regression plot.

After the changes have been reviewed, but before the branch is merged, I'll move some files around to fix the file structure. No code changes will be made at that stage.

2023-12-15 16:05 UTC, nabury requested changes
Just one minor request to add a comment where it's not obvious to me what the code is doing. Looks good!

2023-12-15 16:05 UTC, nabury commented on R/meta_regression_plots.R
> +#' Defaultsa to "BR"
Typo

2023-12-21 09:53 UTC, JanionNevill commented on R/meta_regression/composite_regression_plot.R
> +
Added

2023-12-21 09:54 UTC, JanionNevill commented on R/meta_regression_plots.R
> +#' Defaultsa to "BR"
Good spot. Fixed.

2023-12-21 10:21 UTC, nabury approved these changes

2023-12-21 10:38 UTC, merged