Mr 26 covariate tabs
CRSU-Apps/MetaInsight pull request #124
Opened 2024-01-11 16:56 UTC by BalancedmonkeY

Addition of the standard Bayesian tabs that contain the treatment comparisons for any pair, and the ranking panels.

Note: there is a known bug in the Radial SUCRA plot where it will sometimes not draw the network (which is the case for the test data sets). This bug has been fixed on the main app, and the fix will be included once the meta-regression feature is released in Beta.

2024-01-12 13:10 UTC, tommorris168 requested changes
No comments on the code, all looks good.

Two issues:

1. In tab 4c-3, the download on the leftmost panel is putting the . in the file name in the wrong place, so the file type is wrong.
2. Fixed effects models for shared or unrelated covariate parameters aren't working. I have checked the previous branch (mr-19) and it was working then, so whatever is wrong has been introduced in this branch.

2024-01-23 16:36 UTC, BalancedmonkeY commented
Reminder to myself to also add unit tests for slope/intercept code that I implemented for Janion's regression slope

2024-01-30 12:01 UTC, tommorris168 requested changes
Plots download properly now and the fixed effects models work.

2024-02-01 16:45 UTC, BalancedmonkeY commented on R/gemtc_analysis.R
> +  intercepts <- summary$summaries$statistics[1:(nrow(model$model$network$treatments)-1),1]
I didn't do it quite the same way as the slops, but I have made it now that the intercepts are grabbed by their name (i.e. presence of 'd.').

2024-02-01 16:45 UTC, BalancedmonkeY commented on R/gemtc_analysis.R
> +  slopes <- summ$summaries$statistics[slope_indices, 1]  / model$model$regressor$scale
Added the "Mean" to both slopes and intercepts - thanks.

And yes, the scale calculation was something that Janion picked up.

2024-02-02 09:05 UTC, tommorris168 requested changes
Sorry, another change. I've just looked at the forest plots in gemtc and bnma, and they both use the median, not the mean. To be consistent I think we should use the median in the novel plot as well. So we want ...$summaries$quantiles[row_index, "50%"].

2024-02-02 09:20 UTC, BalancedmonkeY commented
> Sorry, another change. I've just looked at the forest plots in gemtc and bnma, and they both use the median, not the mean. To be consistent I think we should use the median in the novel plot as well. So we want ...$summaries$quantiles[row_index, "50%"].

Done - and no worries, this does make sense. Also, this may actually help with some of Janion's tests!

2024-02-02 09:24 UTC, tommorris168 approved these changes

2024-02-02 10:45 UTC, merged