MR-3 Added support to data upload for covariate columns in the data
CRSU-Apps/MetaInsight pull request #85
Opened 2023-10-11 07:26 UTC by JanionNevill

I've not updated the text in the data upload tab(s) because the data upload could still change. I have raised Jira issue MR-10 to updated the instructions at the end of the project, when the upload is finalised.

2023-10-17 15:41 UTC, BalancedmonkeY requested changes
Code looked fine. Tests ran fine. App did not - all main functionality failed to work. After looking at console, gave the following error:
`Warning in rbind("T", "N", "Mean", "SD", c("covar", "group"), c("T", "2",  :
  number of columns of result is not a multiple of vector length (arg 5)`

This indicated to me that it was struggling have a dot in the covariate name (as per design). Once I changed this to an underscore, the app ran fine.

Testing done using ContOutBinCov dataset found with Jira item mr-5.

2023-10-19 09:25 UTC, BalancedmonkeY requested changes
All seems to be functioning well.
Only suggestion is to add unit tests for new functions you created.

2023-10-19 14:59 UTC, JanionNevill commented on R/DataWrangling.R
> +RemoveCovariates <- function(data) {
Yep, well remembered

2023-10-19 15:17 UTC, BalancedmonkeY approved these changes
Tests looked complete and I've checked that they've passed :D

2023-10-20 07:17 UTC, merged