Mr 2 gemtc data
CRSU-Apps/MetaInsight pull request #91
Opened 2023-10-26 15:46 UTC by BalancedmonkeY

2023-10-27 14:09 UTC, JanionNevill requested changes

2023-10-31 10:47 UTC, BalancedmonkeY commented on R/DataWrangling.R
> +                                      names_pattern = "(.*).(.)",
Thanks - altered.

2023-10-31 10:48 UTC, BalancedmonkeY commented on R/DataWrangling.R
> +  return(as.data.frame(long_data[,names(long_data)!="arm"]))
Thanks - the addition of 'arm' was a workaround, so glad to remove that step

2023-10-31 10:49 UTC, BalancedmonkeY commented on R/gemtc_analysis.R
> +#' @param cov_friendly Friendly version of chosen covariate
Amended

2023-10-31 10:50 UTC, BalancedmonkeY commented on R/gemtc_analysis.R
> +#' @return list containing two dataframes: 1 of core data, another for covariate data
Added

2023-10-31 10:57 UTC, BalancedmonkeY commented on R/gemtc_analysis.R
> +  return(list(armData=armData,studyData=studyData))
Added spaces throughout all new functions etc.

2023-10-31 10:57 UTC, BalancedmonkeY commented on R/DataWrangling.R
> +      select(starts_with(c("T","R","N")))
Done

2023-10-31 10:58 UTC, BalancedmonkeY commented on R/DataWrangling.R
> +  return(as.data.frame(long_data[,names(long_data)!="arm"]))
Line removed

2023-10-31 10:58 UTC, BalancedmonkeY commented on tests/testthat/test-gemtc_analysis.R
> +  )
Done

2023-10-31 11:04 UTC, BalancedmonkeY commented on tests/testthat/test-gemtc_analysis.R
> +  expect_equal(gemtc_data, expected_data)
Good to know - I think I have done this now?

2023-10-31 11:21 UTC, JanionNevill approved these changes

2023-10-31 11:39 UTC, merged