Mi 31 tidying fn analysis
CRSU-Apps/MetaInsight pull request #94
Opened 2023-11-01 13:28 UTC by tommorris168

All changes made in fn_analysis.R, so that you can see what has changed. If you are happy with it, please request changes in your review and I will then put the functions into the different files.

2023-11-02 15:34 UTC, BalancedmonkeY requested changes
Just some minor suggestions

2023-11-02 15:34 UTC, BalancedmonkeY commented on R/analysis_generic.R
> +# Inputting the data in long form
Duplicate comment

2023-11-02 15:34 UTC, BalancedmonkeY commented on R/analysis_generic.R
> +bugsnetdata <- function(data, metaoutcome, treatment_list){
Would it be possible to add a line just very briefly saying what `bugsnetdata` does?

2023-11-06 16:28 UTC, tommorris168 commented on R/fn_analysis.R
> +#'  - 'treat_list2' = Same as @param treat_list (TM: Not sure why this is here)
I'm guessing that used to be the case, in pre-Janion days. I've gone backwards through all the functions that deal with treat_list, and the original one is CreateTreatmentIds in DataWrangling.R, which returns treat_list as a data frame.

2023-11-06 16:28 UTC, tommorris168 commented on R/fn_analysis.R
> +  } # Nothing returned when either of these is the outcome type. (TM: Function never called in these cases?)
Done.

2023-11-14 11:08 UTC, BalancedmonkeY approved these changes

2023-11-15 11:56 UTC, merged