Mi 30 modularise analysis tab
CRSU-Apps/MetaInsight pull request #95
Opened 2023-11-02 08:46 UTC by JanionNevill

Each of the tabs on the data analysis page has been split into a dedicated tab, as well as the sidebar containing the options.

2023-11-07 15:18 UTC, BalancedmonkeY requested changes
Code ran fine.

Suggested changes are only relating to roxygen comments

2023-11-09 08:08 UTC, JanionNevill commented on R/bayesian_analysis_panel.R
> +#' @param metaoutcome Reactive containing meta analysis outcome: "continuous" or "binary"
Thanks, fixed.

2023-11-09 08:11 UTC, JanionNevill commented on R/bayesian_analysis_panel.R
> +#' @param freq_sub Reactive containing frequentist meta-analysis
Thanks, fixed.

2023-11-09 08:12 UTC, JanionNevill commented on R/data_analysis_options_panel.R
> +#' @param metaoutcome Reactive containing meta analysis outcome: "continuous" or "binary"
Done.

2023-11-09 08:13 UTC, JanionNevill commented on R/data_analysis_options_panel.R
> +#' @param metaoutcome Reactive containing meta analysis outcome: "continuous" or "binary"
Done.

2023-11-09 08:29 UTC, BalancedmonkeY approved these changes

2023-11-09 08:31 UTC, merged